### PR TITLE
Migrate to the tm4c123x-hal crate

### PR DESCRIPTION
**Pull request by mokomull**
This was primarily motivated because the existing dependencies bring in untagged-option, which no longer compiles on nightlies due to

```
error[E0740]: unions may not contain fields that need dropping
  --> /home/mmullins/.cargo/registry/src/github.com-1ecc6299db9ec823/untagged-option-0.1.1/src/lib.rs:53:5
   |
53 |     pub some: T,
   |     ^^^^^^^^^^^
   |
note: `std::mem::ManuallyDrop` can be used to wrap the type
  --> /home/mmullins/.cargo/registry/src/github.com-1ecc6299db9ec823/untagged-option-0.1.1/src/lib.rs:53:5
   |
53 |     pub some: T,
   |     ^^^^^^^^^^^
```

Fortunately, after upgrading the crates this now builds on **stable** Rust.

The example code is dependent on https://github.com/rust-embedded-community/tm4c-hal/pull/28, and also drops the reporting of the elapsed-time in exchange for using the SysTick timer for delays.

I'm not 100% sure this is what the API should end up looking like; I'm looking for early feedback and I'm completely open to suggestions.

### CODE REVIEW

**Comment by mokomull** [comment]
github's pull request seems to have shredded the rendering of the ordering of commits, as well.  It's really

```
% git log master.. --reverse --oneline  
48c8f54 cargo fmt
2c16b6a Migrate to the tm4c123x-hal crate
456a54f examples: convert to the new Board API
409a538 Remove the r0 dep
73be8ed (HEAD -> tm4c123x-hal, mokomull/tm4c123x-hal) remove use of #[feature()]
```

I was conflicted whether to squash the examples into the migration, because it does break `git bisect`-ability.

**Review by thejpster — APPROVED** [review]
LGTM!

**Comment by thejpster** [comment]
@mokomull, could you take a look at the Travis error?

**Comment by thejpster** [comment]
Ah, as you said, this is blocked on https://github.com/rust-embedded-community/tm4c-hal/pull/28 because of the example.

**Comment by thejpster** [comment]
This builds now. Hurrah!

**Pull request merged**
